### ISSUE TITLE
Cool plugin!

### ISSUE THREAD

**Issue by scottopolis** [josephsellers/rcp-hollerbox#1]
Thanks for your work here Joseph.  Just a couple things: you are overwriting some core Holler Box functions, which is gonna cause problems.  In version 0.6 I am changing up a lot of that func, but also adding a display filter. You can use that instead of ovewriting maybe_display_items:

// if show_it is true, that means we display this notification. $box_id is holler box id
$show_it = apply_filters( 'hwp_display_notification', $show_it, $box_id, $post_id  );

Also there are hooks in display_notification_box if you need them.  I'm happy to add more hooks and filters, just let me know where you need them.

Cheers!

**Comment by iammahmudur** [comment]
Hi Scott,

Thanks for your message. 

Core functions have been overwritten due to lack of extensibility in the plugin, which was required for this particular requirement. Having said that, I am happy to revise the code when new hooks are available. I am eagerly looking forward to get the new functionalities on the upcoming version.

I have also noticed few issues that I am going to explain you in details very soon.

Thanks again.

**Comment by iammahmudur** [comment]
Hi Scott,

I hope you are doing great.

We have just released a new version. We have removed the custom code and using the new Hollerbox hook **hwp_display_notification** for controlling the notification based on RCP status.

Thanks again.

**Comment by scottopolis** [comment]
Awesome!

**Comment by iammahmudur** [comment]
Hi Scott,

I have told you previously about an issue with Hollerbox that I have noticed:

> I have also noticed few issues that I am going to explain you in details very soon.

Please find the details as given below:

```
To create a Hollerbox notification we need to create a holler box post. But it conflicts with multiple notification on the same page. For example. If I create a Hollerbox for `Everyone` and create another Hollerbox for the `Paying Member` only.  So when `Paying Members` visit the site they will see both notification. But only 1 will be active with the toggle button. So if user close the both notification he/she will able see only 1 notification again. There will be no button to toggle the other one. Please check the  screenshots. 
When both notification showing. 
https://prnt.sc/g0cdlb
After closing both notification. 
https://prnt.sc/g0ce13

The issue is the button is there. but the opacity is 0 as the holler box JS targets elements by id. So it only works for a single element.

It's more problematic when both notification are in same position. In that case both of them stays on top of each other.
```

Please let me know if you need more information regarding this.

Thanks again,

Mahmudur

**Comment by scottopolis** [comment]
Hi, I think I know the issue. Do you mind posting it here: https://github.com/scottopolis/holler-box/issues

**Comment by iammahmudur** [comment]
Done and posted.
https://github.com/scottopolis/holler-box/issues/4#issue-247353503
