### ISSUE TITLE
If a user has interacted in a Holler Box, store in metadata rather than cookies

### ISSUE THREAD

**Issue by josephsellers** [josephsellers/rcp-hollerbox#2]
Since this plugin links Holler Box with RCP I would like to store the fact that someone has dismissed or interacted with a specific Holler in their Meta rather than in cookies. That way, if a user has already interacted or dismissed but then visits from a different device they are not prompted to answer again.

**Comment by volodymyr-tsaryk** [comment]
@josephsellers could you please let me know in what cases this box appears, I've seen it couple times but now I can't see it, even I cleaned all cookies

**Comment by josephsellers** [comment]
@volodymyr-tsaryk we create new surveys and display them in Holler Box. Then, once we have got the info, we need we turn them off. We don't currently have any surveys running. 

You could turn on one of the past boxes on the staging site: https://roke.co/wp-admin/edit.php?post_type=hollerbox
